import Footer from './components/Footer'
import Header from './components/Header'
import Navbar from './components/Navbar'
import SearchBox from './components/SearchBox'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <Navbar />
        <div className='absolute top-0 bg-red-900 z-100'>
        <SearchBox />
        </div>
        <div className='pt-20'>
        {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}